spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

# Connection url for the database "netgloo_blog"
spring.datasource.url=${DB_URL:}

# Username and password
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

# Connection to Redis
spring.session.store-type=redis
spring.session.redis.namespace=dptweb:session
spring.session.redis.configure-action=none
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=6379
spring.redis.ssl=${REDIS_SSL:false}